# Generated by Django 6.0.3 on 2026-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='tipo',
        ),
        migrations.AddField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(default='Sem descrição', max_length=100),
            preserve_default=False,
        ),
    ]
